### ISSUE TITLE
[REQ]: www.elindependiente.com

### ISSUE THREAD

**Issue by mikkk3l** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9661] opened 2023-11-27 07:12 UTC
### Website URL

www.elindependiente.com

### What browser are u using?

Chromium 119

### Version

1.1.1

### Notes

Grey overlay avoids browsing due to not accepting cookies.

**Comment by OhMyGuus** [comment] 2023-12-14 09:24
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7273.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:24 UTC
Labels: Website request
