### ISSUE TITLE
[REQ]: www.dropbox.com

### ISSUE THREAD

**Issue by sebastienserre** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5729] opened 2023-07-14 07:59 UTC
### Website URL

www.dropbox.com

### What browser are u using?

Other

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-18 13:04
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3504.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-18 13:04 UTC
Labels: Website request
