### ISSUE TITLE
[REQ]: lepointdevente.com

### ISSUE THREAD

**Issue by fharper** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8827] opened 2023-11-05 17:06 UTC
### Website URL

lepointdevente.com

### What browser are u using?

Chromium 119

### Version

1.1.1

### Notes

Got a popup asking my preferences.

**Comment by OhMyGuus** [comment] 2023-12-14 08:28
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #8826.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:28 UTC
Labels: Website request
