### ISSUE TITLE
[REQ]: www.finnair.com

### ISSUE THREAD

**Issue by Cipherwriter** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10356] opened 2023-12-15 22:40 UTC
### Website URL

www.finnair.com

### What browser are u using?

Firefox 122.0

### Version

1.1.1

### Notes

Gray overlay when cookie warning shows up and I can't do anything about it unless I disable the extension

**Comment by OhMyGuus** [comment] 2023-12-17 02:19
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2634.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-17 02:19 UTC
Labels: Website request
