### ISSUE TITLE
[REQ]: www.hl.co.uk

### ISSUE THREAD

**Issue by bpsib** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5971] opened 2023-07-25 22:58 UTC
### Website URL

www.hl.co.uk

### What browser are u using?

Firefox 115.0

### Version

1.1.1

### Notes

No scrollbar until I disable then dismiss the notice.

**Comment by OhMyGuus** [comment] 2023-12-14 09:35
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3943.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:35 UTC
Labels: Website request
