### ISSUE TITLE
[REQ]: lecrabeinfo.net

### ISSUE THREAD

**Issue by tonytechlabb** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9074] opened 2023-11-11 18:56 UTC
### Website URL

lecrabeinfo.net

### What browser are u using?

Brave

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 09:32
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2580.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:32 UTC
Labels: Website request
