### ISSUE TITLE
[REQ]: www.eurostar.com

### ISSUE THREAD

**Issue by NicoWeio** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9592] opened 2023-11-25 12:12 UTC
### Website URL

www.eurostar.com

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

Hidden banner blocks all interactivity

**Comment by OhMyGuus** [comment] 2023-12-14 09:25
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #8653.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:25 UTC
Labels: Website request
