### ISSUE TITLE
[REQ] www.srf.ch

### ISSUE THREAD

**Issue by cr1za** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9437] opened 2023-11-21 11:53 UTC
**Website URL(s)**

[https://www.srf.ch/](https://www.srf.ch/)

**Browser**
[X] Firefox
[ ] Chrome

**Extension version**
V1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 09:27
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6915.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:27 UTC
Labels: Website request
