### ISSUE TITLE
[REQ]: larian.com

### ISSUE THREAD

**Issue by Sebster3** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6690] opened 2023-08-24 00:56 UTC
### Website URL

larian.com

### What browser are u using?

Firefox 117.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-13 22:24
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5715.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 22:24 UTC
Labels: Website request
