### ISSUE TITLE
[REQ]: www.temu.com

### ISSUE THREAD

**Issue by Cipherwriter** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9118] opened 2023-11-12 18:27 UTC
### Website URL

www.temu.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

### Notes

the extension didn't work for this site

**Comment by OhMyGuus** [comment] 2023-12-14 00:10
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4770.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 00:10 UTC
Labels: Website request
