### ISSUE TITLE
[REQ]: www.perplexity.ai

### ISSUE THREAD

**Issue by j-nkrm** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4256] opened 2023-05-10 16:20 UTC
### Website URL

www.perplexity.ai

### What browser are u using?

Firefox 113.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-05 14:08
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3795.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:08 UTC
Labels: Website request
