### ISSUE TITLE
[REQ]: www.mediamarkt.de

### ISSUE THREAD

**Issue by anga83** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4344] opened 2023-05-14 15:40 UTC
### Website URL

www.mediamarkt.de

### What browser are u using?

Chromium 113

### Version

1.1.1

### Notes

While the extension is enabled on this domain, the page cannot be scrolled. ISDCAC seems to just hide the cookie overlay without simulating a button click, while the page will only allow scrolling once a decision was made.

**Comment by OhMyGuus** [comment] 2023-07-05 13:24
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3694.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 13:24 UTC
Labels: Website request
