### ISSUE TITLE
[REQ]: ai.meta.com

### ISSUE THREAD

**Issue by Dimitris-Konstantakis** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5997] opened 2023-07-27 08:03 UTC
### Website URL

ai.meta.com

### What browser are u using?

Google Chrome 115

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 10:42
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5813.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 10:42 UTC
Labels: Website request
