### ISSUE TITLE
[REQ]: www.br.de

### ISSUE THREAD

**Issue by jensb** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7591] opened 2023-09-27 10:13 UTC
### Website URL

www.br.de

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

Cookie warning is not visible, but I cannot scroll the page until I disable the extension and dismiss the (then visible) warning.

**Comment by OhMyGuus** [comment] 2023-12-13 23:50
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7405.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 23:50 UTC
Labels: Website request
