### ISSUE TITLE
[REQ]: www.akakce.com

### ISSUE THREAD

**Issue by EmirLogas** [OhMyGuus/I-Still-Dont-Care-About-Cookies#3707] opened 2023-04-17 07:44 UTC
### Website URL

www.akakce.com

### What browser are u using?

Firefox 112.0

### Version

1.1.1

### Notes

cookie banner is not blocked.

**Comment by OhMyGuus** [comment] 2023-07-05 14:21
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3458.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:21 UTC
Labels: Website request
