### ISSUE TITLE
[REQ]: www.threads.net

### ISSUE THREAD

**Issue by JohnFarrellDev** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6758] opened 2023-08-26 13:56 UTC
### Website URL

www.threads.net

### What browser are u using?

Firefox 116.0

### Version

1.1.1

### Notes

I'm also using dark theme.

![image](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/29123700/a7a2d6a5-394d-44c5-bb7a-7b007b0d18ad)

**Comment by OhMyGuus** [comment] 2023-12-14 11:35
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5545.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 11:35 UTC
Labels: Website request
