### ISSUE TITLE
[REQ]: www.expressvpn.com

### ISSUE THREAD

**Issue by GrayedFox** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8840] opened 2023-11-06 01:27 UTC
### Website URL

www.expressvpn.com

### What browser are u using?

Chromium 119

### Version

1.1.1

### Notes

Cookie appeared in slide-up banner from bottom of screen :)

**Comment by OhMyGuus** [comment] 2023-12-14 09:34
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6871.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:34 UTC
Labels: Website request
