### ISSUE TITLE
[REQ]: www.foodwatch.org

### ISSUE THREAD

**Issue by jensb** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7672] opened 2023-09-30 10:09 UTC
### Website URL

www.foodwatch.org

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

cookie warning is displayed despite having the extension

**Comment by OhMyGuus** [comment] 2023-12-13 22:25
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7338.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 22:25 UTC
Labels: Website request
