### ISSUE TITLE
[REQ]: lesjoiesducode.fr

### ISSUE THREAD

**Issue by joggee-fr** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4558] opened 2023-05-22 19:27 UTC
### Website URL

lesjoiesducode.fr

### What browser are u using?

Firefox 113.0

### Version

1.1.1

### Notes

I have tested to hide `div#cc-main` but the scrollbar is not working after.

**Comment by OhMyGuus** [comment] 2023-07-05 14:13
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3873.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:13 UTC
Labels: Website request
