### ISSUE TITLE
[REQ]: www.eurostar.com

### ISSUE THREAD

**Issue by P-eMartin** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10424] opened 2023-12-19 14:03 UTC
### Website URL

www.eurostar.com

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

Website not accessible because of extension.

**Comment by Zoriot** [comment] 2023-12-20 11:40
Duplicate of https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/8653.

**Closed** 2023-12-23 21:23 UTC
Labels: Website request, V1.1.1
