### ISSUE TITLE
[REQ]: gls-group.eu

### ISSUE THREAD

**Issue by jrapp2** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8919] opened 2023-11-07 17:58 UTC
### Website URL

gls-group.eu

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 00:08
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6211.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 00:08 UTC
Labels: Website request
