### ISSUE TITLE
[REQ]: www.jackjones.com

### ISSUE THREAD

**Issue by antonot** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8294] opened 2023-10-21 09:01 UTC
### Website URL

www.jackjones.com

### What browser are u using?

Firefox 118.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 08:28
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6077.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:28 UTC
Labels: Website request
