### ISSUE TITLE
[REQ]: librumreader.com

### ISSUE THREAD

**Issue by erakura** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10143] opened 2023-12-09 19:40 UTC
### Website URL

librumreader.com

### What browser are u using?

Chromium 120

### Version

1.1.1

### Notes

Simple popup cookie warning, appearing on all pages, which blocks all interactions until "Accept and continue" or "Decline" is selected. If Decline is selected it will re-appear on every page load until the user accepts.

**Comment by OhMyGuus** [comment] 2023-12-14 00:09
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7651.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 00:09 UTC
Labels: Website request
