### ISSUE TITLE
[REQ]: www.movistar.es

### ISSUE THREAD

**Issue by owolo** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7579] opened 2023-09-26 20:44 UTC
### Website URL

www.movistar.es

### What browser are u using?

Firefox 117.0

### Version

1.1.1

### Notes

On lower part of the screen.

**Comment by OhMyGuus** [comment] 2023-12-14 11:31
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3541.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 11:31 UTC
Labels: Website request
