### ISSUE TITLE
[REQ]: www.awwwards.com

### ISSUE THREAD

**Issue by Theblockbuster1** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5306] opened 2023-06-26 16:16 UTC
### Website URL

www.awwwards.com

### What browser are u using?

Chromium 114

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-05 13:34
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #1336.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 13:34 UTC
Labels: Website request
