### ISSUE TITLE
[REQ]: ezgif.com

### ISSUE THREAD

**Issue by Daivy03** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6826] opened 2023-08-28 15:11 UTC
### Website URL

ezgif.com

### What browser are u using?

Chrome 116

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-13 22:24
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6420.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 22:24 UTC
Labels: Website request
