### ISSUE TITLE
[REQ]: www.mediamarkt.de

### ISSUE THREAD

**Issue by bannert1337** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5392] opened 2023-06-30 10:15 UTC
### Website URL

www.mediamarkt.de

### What browser are u using?

Other

### Version

1.1.1

### Notes

Breaks the site. It can't be scrolled. The cookie banner isn't shown, but becomes visible when disabling the extension.

**Comment by OhMyGuus** [comment] 2023-07-05 13:23
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3694.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 13:23 UTC
Labels: Website request
