### ISSUE TITLE
[REQ]: 1000.menu

### ISSUE THREAD

**Issue by antonot** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4696] opened 2023-05-29 14:24 UTC
### Website URL

1000.menu

### What browser are u using?

Firefox 113.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-05 14:16
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4665.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:16 UTC
Labels: Website request
