### ISSUE TITLE
[REQ]: www.unionen.se

### ISSUE THREAD

**Issue by t08** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8966] opened 2023-11-08 21:57 UTC
### Website URL

www.unionen.se

### What browser are u using?

Firefox 119.0

### Version

1.1.1

### Notes

the cookie promt gets hidden and the site get dim, disable ext solves it

**Comment by OhMyGuus** [comment] 2023-12-14 09:33
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #8496.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:33 UTC
Labels: Website request
