### ISSUE TITLE
[REQ]: www.instagram.com

### ISSUE THREAD

**Issue by bannert1337** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7855] opened 2023-10-06 16:08 UTC
### Website URL

www.instagram.com

### What browser are u using?

Firefox 115.0

### Version

1.1.1

### Notes

![Screenshot 2023-10-06 at 18-08-31 German Hetero Cringe on Instagram Euer täglich Cringe geb ich euch heute](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/58707896/6e6a9929-1dc2-4c68-8ea6-d9a214ff39ed)

**Comment by OhMyGuus** [comment] 2023-12-13 23:52
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3103.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 23:52 UTC
Labels: Website request
