### ISSUE TITLE
[REQ]: assure.ameli.fr

### ISSUE THREAD

**Issue by sebastienserre** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1354] opened 2022-12-27 19:46 UTC
### Website URL

assure.ameli.fr

### What browser are u using?

Firefox 108.0

### Version

1.1.0

**Comment by krystian3w** [comment] 2023-01-20 09:26
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1730 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1730 opened 2 days ago by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1718 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1718 opened 2 days ago by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1716 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1716 opened 2 days ago by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1636 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1636 opened last week by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1415 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1415 opened 3 weeks ago by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1378 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1378 opened 3 weeks ago by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1354 [Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1354 opened 3 weeks ago by [sebastienserre](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3Asebastienserre)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1167 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1167 opened on Dec 15, 2022 by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)
@OhMyGuus
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1155 [Anonymous request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Anonymous+request%22) Requested using the bot[Website request](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+assure.ameli.fr+label%3A%22Website+request%22)
#1155 opened on Dec 14, 2022 by [OhMyGuus-Bot](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues?q=is%3Aissue+is%3Aopen+author%3AOhMyGuus-Bot)

**Comment by krystian3w** [comment] 2023-01-20 09:27
Duplicate of #1155

**Closed** 2023-01-27 20:11 UTC
Labels: Website request
