### ISSUE TITLE
[REQ]: www.wir-machen-druck.de

### ISSUE THREAD

**Issue by NicoWeio** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8424] opened 2023-10-24 22:35 UTC
### Website URL

www.wir-machen-druck.de

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

Scrolling is broken with the extension enabled (the cookie banner doesn't show up).

**Comment by OhMyGuus** [comment] 2023-12-14 09:28
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #8262.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:28 UTC
Labels: Website request
