### ISSUE TITLE
[REQ]: www.bio-rad.com

### ISSUE THREAD

**Issue by thomas-trenz** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6454] opened 2023-08-14 10:20 UTC
### Website URL

www.bio-rad.com

### What browser are u using?

Chromium Version 114.0.5735.110

### Version

1.1.1

### Notes

Just a greyed-out website when the Add-on is active.

**Comment by OhMyGuus** [comment] 2023-12-14 11:36
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5961.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 11:36 UTC
Labels: Website request
