### ISSUE TITLE
[REQ]: winfuture.de

### ISSUE THREAD

**Issue by samuelT2** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7457] opened 2023-09-22 09:50 UTC
### Website URL

winfuture.de

### What browser are u using?

MS Edge

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 08:20
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #1394.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:20 UTC
Labels: Website request
