### ISSUE TITLE
[REQ]: www.hpb.com

### ISSUE THREAD

**Issue by tommymorgan** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9243] opened 2023-11-15 21:37 UTC
### Website URL

www.hpb.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 09:29
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7842.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:29 UTC
Labels: Website request
