### ISSUE TITLE
[REQ]: www.mediamarkt.de

### ISSUE THREAD

**Issue by ItsNiceCraft** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6022] opened 2023-07-28 11:03 UTC
### Website URL

www.mediamarkt.de

### What browser are u using?

Microsoft Edge 115

### Version

1.1.1

### Notes

Scrolling doesn't work

**Comment by OhMyGuus** [comment] 2023-12-13 22:27
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3694.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 22:27 UTC
Labels: Website request
