### ISSUE TITLE
[REQ]: www.dropbox.com

### ISSUE THREAD

**Issue by tinkicker** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8586] opened 2023-10-30 02:10 UTC
### Website URL

www.dropbox.com

### What browser are u using?

Google Chrome 118

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 08:17
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3504.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:17 UTC
Labels: Website request
