### ISSUE TITLE
[REQ]: www.presse-citron.net

### ISSUE THREAD

**Issue by azgaresncf** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8092] opened 2023-10-14 10:53 UTC
### Website URL

www.presse-citron.net

### What browser are u using?

Firefox

### Version

1.0.5

### Notes

we should delete this css code
![image](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/50982832/51b1ed72-f684-4de6-a243-c278152d5de3)

**Comment by azgaresncf** [comment] 2023-10-14 11:04
There is even better tip.
Presse-citron is part of the ["Consent Framework"](https://www.consentframework.com/#/), like **5000** other websites (https://cdn.sirdata.io/cmp/provider-websites.json).

And the extension bypass the CMP window for Valeurs actuelles. So we can find a solution! :)

**Comment by OhMyGuus** [comment] 2023-12-14 09:29
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6103.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:29 UTC
Labels: Website request
