### ISSUE TITLE
[REQ]: store.duolingo.com

### ISSUE THREAD

**Issue by Voklen** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9110] opened 2023-11-12 14:51 UTC
### Website URL

store.duolingo.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 09:31
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7661.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 09:31 UTC
Labels: Website request
