### ISSUE TITLE
[REQ]: nordvpn.com

### ISSUE THREAD

**Issue by C4J3** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7887] opened 2023-10-07 16:31 UTC
### Website URL

nordvpn.com

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

I imagine this is a pretty standard one. 

![](https://bit.ly/46H4yRw)

![](https://bit.ly/3Q37wKJ)

**Comment by OhMyGuus** [comment] 2023-12-14 08:23
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3271.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:23 UTC
Labels: Website request
