### ISSUE TITLE
[REQ]: www.doctolib.de

### ISSUE THREAD

**Issue by jraxxo** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4108] opened 2023-05-03 15:11 UTC
### Website URL

www.doctolib.de

### What browser are u using?

Firefox 111.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-05 14:15
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2857.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:15 UTC
Labels: Website request
