### ISSUE TITLE
[REQ]: www.ovh.com

### ISSUE THREAD

**Issue by skynet2982** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6180] opened 2023-08-03 11:55 UTC
### Website URL

www.ovh.com

### What browser are u using?

Firefox 116.0

### Version

1.1.1

### Notes

On https://www.ovh.com/manager/#/hub

**Comment by OhMyGuus** [comment] 2023-12-14 11:38
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #756.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 11:38 UTC
Labels: Website request
