### ISSUE TITLE
[REQ]: www.coinbase.com

### ISSUE THREAD

**Issue by Rightmanj** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2815] opened 2023-03-07 13:02 UTC
### Website URL

www.coinbase.com

### What browser are u using?

Not A(Brand 24

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-05 14:18
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2780.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:18 UTC
Labels: Website request
