### ISSUE TITLE
[REQ]: hypixel.net

### ISSUE THREAD

**Issue by EliTheCoder** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7972] opened 2023-10-10 21:43 UTC
### Website URL

hypixel.net

### What browser are u using?

Firefox 118.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 11:07
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4512.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 11:07 UTC
Labels: Website request
