### ISSUE TITLE
[REQ]: nordvpn.com

### ISSUE THREAD

**Issue by nrf83** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7560] opened 2023-09-26 08:07 UTC
### Website URL

nordvpn.com

### What browser are u using?

Firefox 115.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-14 08:23
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3271.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:23 UTC
Labels: Website request
