### ISSUE TITLE
[REQ]: www.nytimes.com

### ISSUE THREAD

**Issue by hensou** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5028] opened 2023-06-13 08:41 UTC
### Website URL

www.nytimes.com

### What browser are u using?

Firefox 115.0

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-07-05 14:07
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3128.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:07 UTC
Labels: Website request
