### ISSUE TITLE
[REQ]: www.bresser.de

### ISSUE THREAD

**Issue by cptechnik** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8659] opened 2023-11-01 00:05 UTC
### Website URL

www.bresser.de

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

unusuable
website is grayout

**Comment by OhMyGuus** [comment] 2023-12-14 08:28
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6700.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:28 UTC
Labels: Website request
