### ISSUE TITLE
[REQ]: www.nectar.com

### ISSUE THREAD

**Issue by benbristow** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8061] opened 2023-10-13 12:35 UTC
### Website URL

www.nectar.com

### What browser are u using?

Microsoft Edge (Version 117.0.2045.60 (Official build) (64-bit)

### Version

1.1.1

### Notes

Website doesn't display at all

**Comment by OhMyGuus** [comment] 2023-12-14 11:06
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3089.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 11:06 UTC
Labels: Website request
