### ISSUE TITLE
[REQ]: www.youtube.com

### ISSUE THREAD

**Issue by bpsib** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7468] opened 2023-09-22 15:12 UTC
### Website URL

www.youtube.com

### What browser are u using?

Firefox 117.0

### Version

1.1.1

### Notes

Can't unpause the video when extension is active.

**Comment by OhMyGuus** [comment] 2023-12-14 00:08
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2639.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 00:08 UTC
Labels: Website request
