### ISSUE TITLE
[REQ]: www.sw-lindau.de

### ISSUE THREAD

**Issue by AndriyAstakhov** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2587] opened 2023-02-26 12:10 UTC
### Website URL

www.sw-lindau.de

### What browser are u using?

Latest Chrome on Windows 11

### Version

1.1.1

### Notes

gray overlay

**Comment by OhMyGuus** [comment] 2023-07-05 14:59
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2586.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-07-05 14:59 UTC
Labels: Website request
