### ISSUE TITLE
[REQ]: www.lcsc.com

### ISSUE THREAD

**Issue by salfter** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10269] opened 2023-12-13 16:10 UTC
### Website URL

www.lcsc.com

### What browser are u using?

Chromium 120

### Version

1.1.1

**Comment by OhMyGuus** [comment] 2023-12-13 22:17
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #9703.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-13 22:17 UTC
Labels: Website request
