### ISSUE TITLE
[REQ]: www.saturn.de

### ISSUE THREAD

**Issue by NicoWeio** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9578] opened 2023-11-24 21:14 UTC
### Website URL

www.saturn.de

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

Scrolling doesn't work

**Comment by OhMyGuus** [comment] 2023-12-14 08:29
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3984.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible

**Closed by OhMyGuus** 2023-12-14 08:29 UTC
Labels: Website request
